### ISSUE TITLE
Docker compose does not specify a syntax version

### ISSUE THREAD

**Issue by TravisBowers** [TensorWorks/Buccaneer#1]
The `docker-compose.yml` example is missing a syntax version specification. This will cause it to fail with `Unsupported config option` errors with some versions of docker-compose. 

Currently, with docker-compose version 1.25.0, the compose file fails with:

```
# docker-compose up
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for networks: 'buccaneer'
Unsupported config option for volumes: 'eventslogs'
Unsupported config option for services: 'grafana'
```

Adding `version: '2.3'` to the beginning of the compose file appears to resolve this issue.

**Comment by Belchy06** [comment]
Thanks for this. I had the changes on my machine but just hadn't committed them or pushed them yet 🤦.

This issue is resolved with https://github.com/TensorWorks/Buccaneer/commit/845e6b94c71630f826eb9123bfc7dd2e8b4372f1
